// USER TYPE
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const SET_PHOTO_URL = "SET_PHOTO_URL";

// CHATROOM TYPE
export const SET_CURRENT_CHAT_ROOM = "SET_CURRENT_CHAT_ROOM";
